### ISSUE TITLE
Error querying indexed cache with lifespan after expiration ('instance cannot be null')

### ISSUE THREAD

**Issue by pzapataf** [infinispan/infinispan#13194]
### Describe the bug

Some type of queries (likely aggregation) fail when they hit recently expired entries with lifespan. The error reported is:
java.lang.IllegalArgumentException: instance cannot be null.
An example of such queries is  'select count(status)  from test.Task t group by status'

### Steps to reproduce with Infinispan 15.0.10

From the console:

1. Create schema test.proto (see schema below)
2. Create the cache TEST_TASKS (see xml below)
3. Add one entry to the cache, with **LIFESPAN**=30 secs
```
{
  "_type": "test.Task",
  "id": 111,
  "type": "test 1",
  "status": "status1"
}
```

4. Run the following query multiple times until it fails during expiration:
   select count(status)  from test.Task t group by status
   
5. When the entry expires, a REST error is generated:
   {"error":{"message":"Error executing search","cause":"instance cannot be null"}}

Unfortunately there's no error thrown by Infinispan (likely the REST endpoint is swallowing the exception).

This also happens from Hot Rod (see exception details in additional information)

### Protobuf schema
```
// test.proto


syntax = "proto2";
package test;

/**
 * @Indexed
 */
message Task {

   /**
    * @Basic(projectable=true, sortable=true)
    */
   required int64 id = 1;

   required string type = 2;

   /**
    * @Keyword
    */
   optional string status = 5 [default = "WAITING"];

}

```

### Cache configuration
```
<?xml version="1.0"?>
<distributed-cache name="TEST_TASKS" owners="1" mode="SYNC" remote-timeout="17500" statistics="true">
	<encoding>
		<key media-type="application/x-protostream"/>
		<value media-type="application/x-protostream"/>
	</encoding>
	<locking concurrency-level="1000" acquire-timeout="15000" striping="false"/>
	<expiration lifespan="-1"/>
	<memory storage="HEAP" max-count="1000"/>
	<persistence passivation="false">
		<file-store purge="false" read-only="false"/>
	</persistence>
	<indexing enabled="true" storage="filesystem">
		<indexed-entities>
			<indexed-entity>test.Task</indexed-entity>
		</indexed-entities>
	</indexing>
	<state-transfer timeout="60000"/>
</distributed-cache>
```

### Additional information

2024-11-02 16:30:03,714 ERROR [o.i.s.h.BaseRequestProcessor] ISPN005003: Exception reported java.lang.IllegalArgumentException: instance cannot be null
at org.infinispan.objectfilter.impl.ObjectFilterImpl.filter(ObjectFilterImpl.java:199)
at org.infinispan.query.core.impl.MetadataHybridQuery.filter(MetadataHybridQuery.java:48)
at org.infinispan.query.core.impl.MappingEntryIterator.transform(MappingEntryIterator.java:63)
at org.infinispan.query.core.impl.MappingEntryIterator.updateNext(MappingEntryIterator.java:45)
at org.infinispan.query.core.impl.MappingEntryIterator.hasNext(MappingEntryIterator.java:27)
at org.infinispan.query.core.impl.MappingIterator.updateNext(MappingIterator.java:54)
at org.infinispan.query.core.impl.MappingIterator.hasNext(MappingIterator.java:38)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
at org.infinispan.query.core.impl.AggregatingQuery.getBaseIterator(AggregatingQuery.java:59)
at org.infinispan.query.core.impl.HybridQuery.getInternalIterator(HybridQuery.java:57)
at org.infinispan.query.core.impl.BaseEmbeddedQuery.executeInternal(BaseEmbeddedQuery.java:101)
at org.infinispan.query.core.impl.BaseEmbeddedQuery.execute(BaseEmbeddedQuery.java:80)
at org.infinispan.query.core.impl.HybridQuery.execute(HybridQuery.java:68)
at org.infinispan.query.core.impl.DelegatingQuery.execute(DelegatingQuery.java:110)
at org.infinispan.query.remote.impl.BaseRemoteQueryManager.executeQuery(BaseRemoteQueryManager.java:63)
at org.infinispan.query.remote.impl.QueryFacadeImpl.query(QueryFacadeImpl.java:45)
at org.infinispan.server.hotrod.HotRodServer.query(HotRodServer.java:151)
at org.infinispan.server.hotrod.CacheRequestProcessor.queryInternal(CacheRequestProcessor.java:542)
at org.infinispan.server.hotrod.CacheRequestProcessor.lambda$query$21(CacheRequestProcessor.java:537)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by fax4ever** [comment]
Thanks @pzapataf for opening this issue.
I just sent a PR to address it.
This is my first PR addressing a GitHub issue. I hope I didn't make mistakes. :P
