### ISSUE TITLE
 Inability to Iterate Over Entries in SIFS-Backed Multimap

### ISSUE THREAD

**Issue by stephankoelle** [infinispan/infinispan#13248]
### Describe the bug

Iterating over keyset of SIFS is problematic

### Expected behavior

It should be possible to iterate over entries in a SIFS-backed multimap directly. However, this functionality fails when dealing with a large number of entries (approximately 30 million). As a workaround, it should still be possible to iterate over the keyset and fetch each entry individually.

The issue becomes apparent after extended usage or when the multimap grows beyond a certain threshold, leading to the following problems:

Iteration over the keyset becomes unreliable.

Using the work around, to fetch each segment, and not full index in one step:
```
 try {
    log.info("Clone segment: {}", segment);
    org.infinispan.commons.util.IntSet intSet = IntSets.immutableSet(segment);
    CloseableIteratorSet<String> keySet = remoteEventCacheOffline.keySet(intSet);
    Set<String> keys = keySet.stream() //
            .collect(Collectors.toSet());
    return keys;
}catch (Exception ex) {
    log.info("IllegalStateException add to retry set: {} : {}", segment, ex.getMessage());
    retrySet.add(segment);
}
```

### Actual behavior

We get a exception, interesting is that: "Segment 116" - When actually segment 7 was exported with the above code.

```
2024-12-02 16:20:11,829 WARN  [org.infinispan.HOTROD] (HotRod-client-async-pool-4-71) ISPN004098: Closing connection [id: 0x468fb385, L:/49.12.*2.*:33238 - R:49.12.*.*/49.12.*.*:11222] due to transport error: java.lang.IllegalStateException: Segment 116 already completed
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.iteration.SegmentKeyTracker.track(SegmentKeyTracker.java:66)
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.operations.IterationNextOperation.acceptResponse(IterationNextOperation.java:120)
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:153)
at deployment.inbound-ear-5.9.2138.ear//org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94)
at deployment.inbound-ear-5.9.2138.ear//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at deployment.inbound-ear-5.9.2138.ear//io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
at deployment.inbound-ear-5.9.2138.ear//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
at deployment.inbound-ear-5.9.2138.ear//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at deployment.inbound-ear-5.9.2138.ear//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [java.base:]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [java.base:]
at java.base/java.lang.Thread.run(Thread.java:833) [java.base:
```

### Infinispan version or git rev

quay.io/infinispan/server:15.0.10.Final-1

**Comment by stephankoelle** [comment]
One full loop over all segment, with one retry of the faile ones:
`IllegalStateException add to retry set: 2 : Segment 0 already completed
IllegalStateException add to retry set: 7 : Segment 116 already completed
IllegalStateException add to retry set: 11 : Segment 6 already completed
IllegalStateException add to retry set: 12 : Segment 9 already completed
IllegalStateException add to retry set: 13 : Segment 9 already completed
IllegalStateException add to retry set: 24 : Segment 19 already completed
IllegalStateException add to retry set: 25 : Segment 22 already completed
IllegalStateException add to retry set: 31 : Segment 29 already completed
IllegalStateException add to retry set: 32 : Segment 30 already completed
IllegalStateException add to retry set: 33 : Segment 30 already completed
IllegalStateException add to retry set: 36 : Segment 34 already completed
IllegalStateException add to retry set: 37 : Segment 35 already completed
IllegalStateException add to retry set: 40 : org.infinispan.commons.CacheException: Error reading header from 6096:10141981 | 0
IllegalStateException add to retry set: 41 : Segment 39 already completed
IllegalStateException add to retry set: 44 : Segment 42 already completed
IllegalStateException add to retry set: 45 : Segment 43 already completed
IllegalStateException add to retry set: 48 : Segment 46 already completed
IllegalStateException add to retry set: 49 : Segment 47 already completed
IllegalStateException add to retry set: 53 : Segment 51 already completed
IllegalStateException add to retry set: 56 : Segment 54 already completed
IllegalStateException add to retry set: 57 : Segment 55 already completed
IllegalStateException add to retry set: 61 : Segment 59 already completed
IllegalStateException add to retry set: 66 : Segment 21 already completed
IllegalStateException add to retry set: 67 : Segment 64 already completed
IllegalStateException add to retry set: 72 : Segment 70 already completed
IllegalStateException add to retry set: 76 : Segment 74 already completed
IllegalStateException add to retry set: 77 : Segment 75 already completed
IllegalStateException add to retry set: 78 : Segment 75 already completed
IllegalStateException add to retry set: 79 : Segment 75 already completed
IllegalStateException add to retry set: 82 : Segment 80 already completed
IllegalStateException add to retry set: 83 : Segment 73 already completed
IllegalStateException add to retry set: 100 : Segment 81 already completed
IllegalStateException add to retry set: 101 : Segment 98 already completed
IllegalStateException add to retry set: 104 : Segment 99 already completed
IllegalStateException add to retry set: 105 : Segment 102 already completed
IllegalStateException add to retry set: 110 : Segment 107 already completed
IllegalStateException add to retry set: 111 : Segment 108 already completed
IllegalStateException add to retry set: 118 : Segment 112 already completed
IllegalStateException add to retry set: 119 : Segment 113 already completed
IllegalStateException add to retry set: 123 : Segment 120 already completed
IllegalStateException add to retry set: 131 : Segment 129 already completed
IllegalStateException add to retry set: 132 : Segment 130 already completed
IllegalStateException add to retry set: 135 : Segment 193 already completed
IllegalStateException add to retry set: 136 : Segment 134 already completed
IllegalStateException add to retry set: 153 : Segment 151 already completed
IllegalStateException add to retry set: 154 : Segment 152 already completed
IllegalStateException add to retry set: 166 : Segment 54 already completed
IllegalStateException add to retry set: 167 : Segment 165 already completed
IllegalStateException add to retry set: 180 : org.infinispan.commons.CacheException: Error reading header from 21513:6333329 | 0
IllegalStateException add to retry set: 181 : Segment 61 already completed
IllegalStateException add to retry set: 195 : Segment 193 already completed
IllegalStateException add to retry set: 196 : Segment 194 already completed
IllegalStateException add to retry set: 197 : Segment 194 already completed
IllegalStateException add to retry set: 202 : Segment 122 already completed
IllegalStateException add to retry set: 206 : Segment 203 already completed
IllegalStateException add to retry set: 209 : Segment 207 already completed
IllegalStateException add to retry set: 210 : Segment 208 already completed
IllegalStateException add to retry set: 214 : Segment 205 already completed
IllegalStateException add to retry set: 215 : Segment 212 already completed
IllegalStateException add to retry set: 218 : Segment 213 already completed
IllegalStateException add to retry set: 219 : Segment 217 already completed
IllegalStateException add to retry set: 224 : Segment 201 already completed
IllegalStateException add to retry set: 225 : Segment 222 already completed
IllegalStateException add to retry set: 231 : Segment 228 already completed
IllegalStateException add to retry set: 232 : Segment 229 already completed
IllegalStateException add to retry set: 238 : Segment 235 already completed
IllegalStateException add to retry set: 239 : Segment 236 already completed
IllegalStateException add to retry set: 243 : Segment 241 already completed
IllegalStateException add to retry set: 247 : Segment 245 already completed
IllegalStateException add to retry set: 248 : Segment 246 already completed
IllegalStateException add to retry set: 253 : Segment 251 already completed
IllegalStateException add to retry set: 254 : Segment 252 already completed
IllegalStateException add to retry set: 2 : Segment 252 already completed
IllegalStateException add to retry set: 131 : Segment 252 already completed
IllegalStateException add to retry set: 132 : Segment 252 already completed
IllegalStateException add to retry set: 136 : Segment 135 already completed
IllegalStateException add to retry set: 12 : Segment 7 already completed
IllegalStateException add to retry set: 25 : Segment 192 already completed
IllegalStateException add to retry set: 154 : Segment 153 already completed
IllegalStateException add to retry set: 32 : Segment 31 already completed
IllegalStateException add to retry set: 36 : Segment 33 already completed
IllegalStateException add to retry set: 167 : Segment 166 already completed
IllegalStateException add to retry set: 40 : org.infinispan.commons.CacheException: Error reading header from 6096:10141981 | 0
IllegalStateException add to retry set: 44 : Segment 41 already completed
IllegalStateException add to retry set: 48 : Segment 45 already completed
IllegalStateException add to retry set: 180 : Segment 49 already completed
IllegalStateException add to retry set: 181 : Segment 49 already completed
IllegalStateException add to retry set: 57 : Segment 56 already completed
IllegalStateException add to retry set: 67 : Segment 13 already completed
IllegalStateException add to retry set: 196 : Segment 195 already completed
IllegalStateException add to retry set: 72 : Segment 169 already completed
IllegalStateException add to retry set: 77 : Segment 53 already completed
IllegalStateException add to retry set: 206 : Segment 76 already completed
IllegalStateException add to retry set: 79 : Segment 76 already completed
IllegalStateException add to retry set: 215 : Segment 82 already completed
IllegalStateException add to retry set: 219 : Segment 214 already completed
IllegalStateException add to retry set: 225 : Segment 83 already completed
IllegalStateException add to retry set: 100 : Segment 83 already completed
IllegalStateException add to retry set: 231 : Segment 224 already completed
IllegalStateException add to retry set: 232 : Segment 101 already completed
IllegalStateException add to retry set: 110 : Segment 104 already completed
IllegalStateException add to retry set: 111 : Segment 105 already completed
IllegalStateException add to retry set: 239 : Segment 105 already completed
IllegalStateException add to retry set: 119 : Segment 238 already completed
IllegalStateException add to retry set: 248 : Segment 218 already completed
IllegalStateException add to retry set: 254 : Segment 253 already completed`

I think segment 40 is really broken?
from the server for segment 40:
`Caused by: java.lang.IllegalStateException: Error reading header from 6096:10141981 | 0
at org.infinispan.persistence.sifs.IndexNode$LeafNode.getHeaderAndKey(IndexNode.java:1126)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1294)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1273)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1273)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1273)
at org.infinispan.persistence.sifs.IndexNode.lambda$publish$1(IndexNode.java:1250)
at org.infinispan.reactive.FlowableCreate$BaseEmitter.attemptSubscribe(FlowableCreate.java:338)
at org.infinispan.reactive.FlowableCreate$BaseEmitter.request(FlowableCreate.java:367)
at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.request(FlowableDoFinally.java:108)
at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:123)
at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.request(FlowableConcatMap.java:217)
at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:123)
at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber$Request.run(FlowableSubscribeOn.java:156)
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
... 1 more`

**Comment by wburns** [comment]
> ### Expected behavior
> It should be possible to iterate over entries in a SIFS-backed multimap directly. However, this functionality fails when dealing with a large number of entries (approximately 30 million). As a workaround, it should still be possible to iterate over the keyset and fetch each entry individually.

Just to clarify, are you saying there are two issues here? One is that you were unable to iterate over the entire cache contents and then another that when you tried to iterate over the keys in a given segment is the error here right?

Also can you clarify what you are attempting to do? You mention you want to fetch each entry individually, what do you mean by that?

**Comment by stephankoelle** [comment]
> Just to clarify, are you saying there are two issues here? One is that you were unable to iterate over the entire cache contents and then another that when you tried to iterate over the keys in a given segment is the error here right?

It's not possible to iterate over the entrySet of a multimap.

I want to perform a backup and restore of a SIFS-backed multimap.

Infinispan's backup functionality doesn't work; it faces a similar issue to the entrySet iterator.

As a workaround, I am using this solution.

**Comment by stephankoelle** [comment]
This issue is still present, only producible under read load in production. (we always use lastet release)
After about one week we start getting:
```
2025-09-01 14:13:46,834 WARN  (blocking-thread-infini22.*.de-p2-t9) [org.infinispan.server.iteration.DefaultIterationManager] ISPN005061: Removed unclosed iterator '166'
2025-09-01 19:40:04,998 ERROR (blocking-thread-infini22.*.de-p2-t22) [org.infinispan.SERVER] ISPN005003: Exception reported org.infinispan.commons.CacheException: Error reading header from 19012:5553011 | 0
```
```
Caused by: java.lang.IllegalStateException: Error reading header from 19012:5553011 | 0

at org.infinispan.persistence.sifs.IndexNode$LeafNode.getHeaderAndKey(IndexNode.java:1133)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1303)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1282)
at org.infinispan.persistence.sifs.IndexNode.recursiveNode(IndexNode.java:1282)
at org.infinispan.persistence.sifs.IndexNode.lambda$publish$1(IndexNode.java:1259)
at org.infinispan.reactive.FlowableCreate$BaseEmitter.attemptSubscribe(FlowableCreate.java:338)
at org.infinispan.reactive.FlowableCreate$BaseEmitter.request(FlowableCreate.java:367)
at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.request(FlowableDoFinally.java:108)
at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:123)
at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.request(FlowableConcatMap.java:217)
at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.rxjava3.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:123)
at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber$Request.run(FlowableSubscribeOn.java:156)
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
... 1 more
```
