### ISSUE TITLE
infinispan QueryEngine fails with order by and where statement

### ISSUE THREAD

**Issue by thaefner** [infinispan/infinispan#13478]
### Describe the bug

I have a statement like this: 
```
String select = "SELECT max(v.properties.state), count(v.properties.state) FROM de.cit.intelliform.graph.Vertex v where v.properties.state= 'NEW' or v.properties.state== 'OPEN' group by v.properties.state";
Query<T> query = queryFactory.create(select);
query.execute().list();
```

It fails with following error message:
```
Exception in thread "main" org.infinispan.objectfilter.ParsingException: ISPN028502: Unknown alias: properties.
	at org.infinispan.objectfilter.impl.syntax.parser.QueryResolverDelegateImpl.normalizeUnqualifiedRoot(QueryResolverDelegateImpl.java:101)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.pathedPropertyReferenceSource(QueryResolver.java:7258)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.pathedPropertyReference(QueryResolver.java:7123)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.propertyReferencePath(QueryResolver.java:6982)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.propertyReferenceExpression(QueryResolver.java:5217)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.valueExpressionPrimary(QueryResolver.java:5036)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.valueExpression(QueryResolver.java:4832)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.rowValueConstructor(QueryResolver.java:4110)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.predicate(QueryResolver.java:3076)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.searchCondition(QueryResolver.java:2772)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.searchCondition(QueryResolver.java:2672)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.whereClause(QueryResolver.java:637)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.querySpec(QueryResolver.java:505)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.queryStatement(QueryResolver.java:388)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.queryStatementSet(QueryResolver.java:308)
	at org.infinispan.objectfilter.impl.ql.parse.QueryResolver.statement(QueryResolver.java:241)
	at org.infinispan.objectfilter.impl.ql.QueryParser.resolve(QueryParser.java:81)
	at org.infinispan.objectfilter.impl.ql.QueryParser.parseQuery(QueryParser.java:69)
	at org.infinispan.objectfilter.impl.syntax.parser.IckleParser.parse(IckleParser.java:19)
	at org.infinispan.query.core.impl.QueryEngine.lambda$parse$0(QueryEngine.java:480)
	at org.infinispan.query.core.impl.QueryCache.lambda$get$aa09db55$1(QueryCache.java:76)
	at org.infinispan.cache.impl.FunctionMapper.apply(FunctionMapper.java:43)
	at org.infinispan.interceptors.impl.CallInterceptor.visitComputeIfAbsentCommand(CallInterceptor.java:449)
	at org.infinispan.commands.write.ComputeIfAbsentCommand.acceptVisitor(ComputeIfAbsentCommand.java:117)
	at org.infinispan.interceptors.impl.CallInterceptor.visitCommand(CallInterceptor.java:178)
```
	
I have analysed the problem and in the code there is a problem at this point:
https://github.com/infinispan/infinispan/blob/main/query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java#L245
At this code pointer there is a where-statement created before the group by happens. There is used a alias "QueryStringCreator.DEFAULT_ALIAS ("_gen0") at this point. But in the where-statement which is generated with SyntaxTreePrinter.printTree(normalizedWhereClause) there is no alias used. So the alias is missing here. 

It happens only if we use own index fields like v.properties.state. If we use annoted fields with @GenericField everything works.

I did a fix at this point:
```
            final String where = SyntaxTreePrinter.printTree(normalizedWhereClause);
            final String replacedWhere = where.replaceAll("(\\b\\w+)\\.", "_gen0.$1.");
            firstPhaseQuery.append(' ').append(replacedWhere);
```
which adds the alias in thewhere statement. I build infinispan and then the query works. But the workaround with the regex is really ugly. It should be solved in general.

### Expected behavior

Statement with where statement and goup by should work with own indexed fields.

### Actual behavior

Query fails

### How to Reproduce?

Create a query like this and execute it:
String select = "SELECT max(v.properties.state), count(v.properties.state) FROM de.cit.intelliform.graph.Vertex v where v.properties.state= 'NEW' or v.properties.state== 'OPEN' group by v.properties.state";

### Infinispan version or git rev

It should be 15 and 14

**Comment by fax4ever** [comment]
Hi @thaefner. Thanks for opening the issue.
Could you provide the mapping of the entity `de.cit.intelliform.graph.Vertex`, for instance posting the annotated Java entity or the Protobuf message definition?

If the field `properites` is multivalued I don't think you can define a group by on it. I think that the group identifier should be a single value (that is identifier of the group).

Let us know!
Fabio

**Comment by thaefner** [comment]
Hallo Fabio, 

the field properties ist not really multivalued, there are other fields under the properties field. So there could be v.properties.state or v.properties.type and so on. And these fields should be groupable. It works with the group statement unless I use a where condition. 
I have attached you stripped down Java class file with the relevant parts. We use a so called PropertyBinder to generate the fields for properties. Have a look at:
[Vertex.txt](https://github.com/user-attachments/files/18209641/Vertex.txt)

Best regards
Tobias

**Comment by fax4ever** [comment]
The properties is a map, so it is a multivalued field.
My advice is to add a property `getState()` that returns `properties.get("state")` and group by on `v.state`, 
we don't support map navigation on property paths.

**Comment by thaefner** [comment]
Ok, I will try it. Do I have to annotate `getState()` with `@GenericField`?

**Comment by fax4ever** [comment]
You should use the Infinispan indexing annotation, see https://infinispan.org/docs/stable/titles/query/query.html#indexing-annotations_indexing-caches. I'm closing the issue.

**Comment by thaefner** [comment]
Thanks for your help and Merry Christmas!
