### ISSUE TITLE
There was a problem moving indexes for compactor with file 180

### ISSUE THREAD

**Issue by chenzhenyang** [infinispan/infinispan#13541]
### Describe the bug

2024-12-22 02:39:13.058 ERROR [blocking-thread--p3-t7] o.i.persistence.sifs.Compactor:682 - There was a problem moving indexes for compactor with file 180
java.lang.IllegalStateException: Too many records for this key (short overflow)
	at org.infinispan.persistence.sifs.IndexNode.copyWith(IndexNode.java:682)
	at org.infinispan.persistence.sifs.IndexNode.setPosition(IndexNode.java:410)
	at org.infinispan.persistence.sifs.IndexNode.setPosition(IndexNode.java:404)
	at org.infinispan.persistence.sifs.Index$Segment.accept(Index.java:529)
	at org.infinispan.persistence.sifs.Index$Segment.accept(Index.java:403)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:403)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by tristantarrant** [comment]
@wburns this may no longer happen after all the changes made to SIFS

**Comment by wburns** [comment]
This was fixed in https://github.com/infinispan/infinispan/pull/11561. The limit was changed from a short (2^15-1) to an int (2^31-1)
